# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LidarForForest
                                 A QGIS plugin
 This plugin links lidar processes via the LidR R package to QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-21
        copyright            : (C) 2024 by Francesco Pirotti, Larissa Falcao Granja
        email                : francesco.pirotti@unipd.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francesco Pirotti, Larissa Falcao Granja'
__date__ = '2024-03-21'
__copyright__ = '(C) 2024 by Francesco Pirotti, Larissa Falcao Granja'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import qgis.gui
import sys
import inspect

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

from qgis.core import (QgsProcessingAlgorithm,
                       QgsSettings,
                       QgsMessageLog,
                       QgsApplication,
                       Qgis)

from .Rsession import Rsession
from .lidar4forest_provider import LidarForForestProvider
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)
#import platform
#from qgis.utils import iface

from .Rsession import *

class LidarForForestPlugin(object):

    def __init__(self, iface):
        self.provider = None
        self.iface = iface
        self.rst = Rsession()

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""

        self.provider = LidarForForestProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def initGui(self):
        self.initProcessing()

    def unload(self):
        #self.rst.giveCommand("q('no')")
        self.rst.stopRsession()
        QgsApplication.processingRegistry().removeProvider(self.provider)
