# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LidarForForest
                                 A QGIS plugin
 This plugin links lidar processes via the LidR R package to QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-03-21
        copyright            : (C) 2024 by Francesco Pirotti, Larissa Falcao Granja
        email                : francesco.pirotti@unipd.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Francesco Pirotti, Larissa Falcao Granja'
__date__ = '2024-03-21'
__copyright__ = '(C) 2024 by Francesco Pirotti, Larissa Falcao Granja'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'
from qgis.gui import (QgsMessageBar)
from qgis.PyQt.QtWidgets import *
from qgis.PyQt.QtGui import *
from qgis.PyQt.uic import *

from qgis.PyQt.QtCore import (QCoreApplication)
from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterFile
from qgis.core import QgsProcessingParameterNumber
from qgis.core import QgsProcessingParameterVectorLayer
from qgis.core import QgsProcessingParameterRasterDestination
from qgis.core import QgsProcessingParameterVectorDestination
from qgis.core import QgsProcessingParameterString
from qgis.core import  *

from qgis.utils import *
from qgis.core import (Qgis, QgsProcessing,
                      QgsSettings,
                        QgsMessageLog,
                        QgsProject,
                        QgsProcessingParameterBoolean,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                        QgsProcessingParameterVectorDestination,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFile,
                       QgsProcessingParameterFeatureSink)

import os

from .Rsession import *
from qgis.utils import iface
import inspect
import pathlib
from pathlib import PureWindowsPath
dirname, filename = os.path.split(os.path.abspath(__file__))
class LidarSetupProject(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    INPUT = 'INPUT'
    PARCELS = 'PARCELS'
    TARIF = 'TARIF'

    TREEPOSITION = 'TREEPOSITION'
    CHM = 'CHM'
    OUTPUT = 'OUTPUT'
    VERBOSE = 'VERBOSE'

    def __init__(self):
        super().__init__()
        self.rst = None

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """


        s = QgsSettings()
        projectFolder1 = s.value("lidar4forests/projectFolder", "")

        #
        proj = QgsProject.instance()
        projectFolder2, type_conversion_ok = proj.readEntry("lidar4forests",
                                                    "projectFolder",
                                                    "")

        # priority to project's info on where the project folder is
        if projectFolder2 == "":
            projectFolder = projectFolder1
        else:
            projectFolder = projectFolder2

        if projectFolder != "" and not os.path.exists(projectFolder):
            iface.messageBar().pushMessage("Warning", "Path of point clouds files not available", level=Qgis.Critical)

        #QgsMessageLog.logMessage("Your plugin code might have some problems", level=Qgis.Warning)
        self.addParameter(
            QgsProcessingParameterFile(
                'folder_with_las_files',
                self.tr('Choose project folder containing point cloud files (only LAS/LAZ supported)'),
                QgsProcessingParameterFile.Folder,
                defaultValue=projectFolder
            )
        )

        self.addParameter(QgsProcessingParameterNumber('output_chm_resolution', 'Output CHM resolution', type=QgsProcessingParameterNumber.Double, minValue=0.1, maxValue=10, defaultValue=1))
        self.addParameter(QgsProcessingParameterVectorLayer('parcels_optionally_with_tarifs', 'Parcels optionally with tarifs', optional=True, types=[QgsProcessing.TypeVectorPolygon], defaultValue=None))
        self.addParameter(QgsProcessingParameterRasterDestination('Chm', 'CHM', createByDefault=True, defaultValue=None))
        self.addParameter(QgsProcessingParameterBoolean('user_las_classification_for_better', 'Use LAS classification (CHM only from tree classes)',  defaultValue=False))
        self.addParameter(QgsProcessingParameterVectorDestination('ParcelsWithEstimatedTotalVolume', 'Parcels with Estimated total Volume', type=QgsProcessing.TypeVectorPoint, createByDefault=True, defaultValue=None))
        self.addParameter(QgsProcessingParameterString('allometry_tarif_reference__function__see_examples', 'Allometry (tarif reference | function) ... see examples)', multiLine=True, defaultValue='1 | v=0.0026*h^2+0.0299*h-0.478\n2 | v=0.007*exp(0.1936*h)\n3 | v=0.0063*exp(0.2119*h) '))

        print("check Rsession1")
        self.rst = Rsession()
        print("check Rsession2")

        self.verbose = True

        self.addParameter(QgsProcessingParameterVectorDestination(
                          'LasTiles',
                          'LAS Tiles',
                          type=QgsProcessing.TypeVectorPolygon,
                          createByDefault=True,
                          optional=False,
                          defaultValue=None))

    def setProgressText(self, feedback, stringin, messageType=Qgis.Info, force=False):
        if self.verbose is True or force:

            if messageType == Qgis.Warning:
                feedback.pushWarning(stringin)
            elif messageType == Qgis.Info:
                feedback.setProgressText(stringin)
            else:
                feedback.setProgressText("("+messageType+"): "+stringin)

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """
        feedback = QgsProcessingMultiStepFeedback(11, feedback)
        names = [layer.name() for layer in QgsProject.instance().mapLayers().values()]
        source = self.parameterAsFile(parameters, 'folder_with_las_files', context)
        rastres = float(parameters['output_chm_resolution'])

        s = QgsSettings()
        s.setValue("lidar4forests/projectFolder", source)
        proj = QgsProject.instance()
        proj.writeEntry("lidar4forests", "projectFolder", source)
        mypath = str(pathlib.Path(source)).replace(os.sep, '/')
        geopackage = PureWindowsPath(os.path.join(mypath, "ctgIndex.gpkg" )).as_posix()
        trees = PureWindowsPath(os.path.join(mypath, "trees%.2f.gpkg" % rastres )).as_posix()
        Exists_geopackage = os.path.exists(geopackage)
        outdir = PureWindowsPath(os.path.join(mypath, "output%.2fm" % rastres )).as_posix()
        if not os.path.exists(outdir):
            os.mkdir(outdir)

        opt_output_files_norm = PureWindowsPath(os.path.join(outdir, "norm_{ORIGINALFILENAME}")).as_posix()
        opt_output_files_dtm  = PureWindowsPath(os.path.join(outdir, "dtm_{ORIGINALFILENAME}")).as_posix()
        opt_output_files_chm  = PureWindowsPath(os.path.join(outdir, "chm_{ORIGINALFILENAME}")).as_posix()
        dtm = outdir + "/rasterize_terrain.vrt"

        QgsMessageLog.logMessage('Creating LAS tiles from LAS files', level=Qgis.MessageLevel.Info)
        if not os.path.exists(geopackage):
            mess = "Be patient, processing catalogue with LidR!!"
            #iface.messageBar().pushMessage("Lidar4Forests: ", mess,   level=Qgis.Info)
            self.setProgressText(feedback, mess)
            ##VERY VERY IMPORTANT TO ADD TWO CARRIAGE RETURNS TO READ AND BREAK IN RSESSION!
            self.rst.giveCommand("ctg <- readLAScatalog(\""+mypath+"\")\r\nsave(ctg, file=\"" +
                                 mypath + "/savedata.rda\")\r\nsf::st_write(sf::st_as_sf(ctg), \"" +
                                 geopackage+"\")\r\n\r\n", feedback)
        else:
            self.rst.giveCommand("load(file=\"" +
                                 mypath + "/savedata.rda\")\r\n\r\n", feedback)
            self.setProgressText(feedback, "LAS tiles already exist so we use existing ones.")

        if feedback.isCanceled():
            return {}

        self.setProgressText(feedback, mypath)

        if 'OpenStreetMap' not in names:
            urlWithParams = 'type=xyz&url=http://a.tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png&zmax=19&zmin=0&crs=EPSG3857'
            rlayer = QgsRasterLayer(urlWithParams, 'OpenStreetMap', 'wms')  # EDIT THIS LINE
            if rlayer.isValid():
                QgsProject.instance().addMapLayer(rlayer)
            else:
                QgsMessageLog.logMessage('invalid OSM layer')

        if "LAS Tiles" in names:
                QgsMessageLog.logMessage('Removing existing LAS Tile layer', level=Qgis.MessageLevel.Warning    )


        if feedback.isCanceled():
            return {}
        self.setProgressText(feedback, "Adding LAS tiles layer")

        out_vlayer = QgsVectorLayer(geopackage, "LAS Tiles")
        mess, success = out_vlayer.loadNamedStyle(dirname + "/extra/styleLAStiles.qml")
        QgsProject.instance().addMapLayer(out_vlayer)

        if feedback.isCanceled():
            return {}
############## DTM ############

        Exists_dtm = os.path.exists(dtm)
        if feedback.isCanceled():
            return {}
        self.setProgressText(feedback, 'Creating DTM from LAS files: ' + os.path.basename(dtm))

        self.rst.giveCommand(
            "opt_output_files(ctg) <- \"" + opt_output_files_dtm + "\"\r\ndtm_tin <- rasterize_terrain(ctg, res = " + str(parameters['output_chm_resolution']) + ", algorithm = lidR::tin())\r\n\r\n",
            feedback)

        out_dtm = QgsRasterLayer(dtm, "DTM res %.2f meters" % rastres)
        mess, success = out_dtm.loadNamedStyle(dirname + "/extra/styleDTM.qml")
        QgsProject.instance().addMapLayer(out_dtm)

        if feedback.isCanceled():
            return {}

        self.setProgressText(feedback, 'Normalizing LAS files: ')

        self.rst.giveCommand(
            "opt_output_files(ctg) <- \"" + opt_output_files_norm + "\"\r\nnlas.ctg <- normalize_height(ctg, tin(), dtm = dtm_tin)\r\n\r\n",
            feedback)

        if feedback.isCanceled():
            return {}

        self.setProgressText(feedback, 'Creating CHM... ')

        self.rst.giveCommand(
            "opt_output_files(ctg) <- \"" + opt_output_files_chm + "\"\r\nchm <- rasterize_canopy(nlas.ctg, res=%.2f, pitfree(thresholds = c(0, 10, 20), max_edge = c(0, 1.5)))\r\n\r\n" % rastres,
            feedback)


        out_chm = QgsRasterLayer(dtm, "CHM res %.2f meters" % rastres)
        mess, success = out_chm.loadNamedStyle(dirname + "/extra/styleCHM.qml")
        QgsProject.instance().addMapLayer(out_chm)

#"opt_output_files(ctg) <- \"" + + "\"\r\nchm <- rasterize_canopy(nlas.ctg, res = 0.5, pitfree(thresholds = c(0, 10, 20), max_edge = c(0, 1.5)))"

        Exists_trees = os.path.exists(trees)

        return {self.OUTPUT: geopackage}


    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Setup project'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return ''


    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return LidarSetupProject()
